resources:
- name: vMiauw-Git
  type: git
  source:
    uri: https://github.com/vChrisR/vMiauw.git

jobs:
- name: unit-tests
  plan:
  - get: vMiauw-Git
    trigger: true
  - task: unit-test-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: go
        args: ["test", "./config/*.go"]
