resources:
- name: vMiauw
  type: git
  source:
    uri: https://github.com/vChrisR/vMiauw.git

jobs:
- name: unit-tests
  plan:
  - get: vMiauw
    trigger: true
  - task: unit-test
    file: vMiauw/ci/unittests.yml
